version: '3.4'
services:
  flask:
    image: flask:0.0.6
    user: 'root'
    volumes:
      - ./ansible:/ansible/playbooks

    
networks:
  netbox-docker_default:
    external: true
    driver: bridge