- hosts: localhost
  gather_facts: no
  tasks:
    - name: copy file 
      shell: "scp ../gitlab/123321/123321.conf admin@192.168.255.3:/123321.auto.rsc"


- hosts: AUTOCPE
  become: yes
  gather_facts: no
  become_method: enable
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_cli_ssh_type: libssh
    command_test: !unsafe /system reset-configuration run-after-reset=123321.rsc
  environment:
    remote_tmp: /
  tasks:
    - name: Check for file transfer
      community.network.routeros_command:
        commands: /file print count-only where name=123321.rsc
      register: config_count
    - set_fact:
        output: "{{ config_count['stdout'][0] }}"
    - debug:
        var: "{{ output}} "
    - name: Apply configuration
      community.network.routeros_command:
        commands: "{{ command_test }}"
      when: output == '1'
        
